### ISSUE TITLE
Add dependency tracking support to the build system

### ISSUE THREAD

**Issue by matheusmoreira** [matheusmoreira/liblinux#3]
The build system must be modified so that it will automatically:

 - [x] Convert pattern rules to generated rules
 - [x] Create a directory for the dependency data
   - #2
 - [x] Use the compiler to generate the information
   - #1
 - [x] Include the generated rules in the build system
